os:
  - osx
  - linux

sudo: required
dist: trusty
language: cpp

compiler:
  - gcc
  - clang

before_script:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install bison ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew link bison --force ; fi'
  - bison --version
  - flex --version
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make test
